<?php include __DIR__."/../_header.phtml"; ?>
<?php /** @var Domains_Base $data */ ?>
<?php if ($data) { ?>

    <form>
        </div>
        <div class="form-group">
            <label>Name</label>
            <input type="text" id="name" class="form-control"
                   value="<?=$data->name?>">
        </div>
        <div class="form-group">
            <label>Artist</label>
            <input type="text" id="artist" class="form-control"
                   value="<?=$data->artist?>">
        </div>
        <div class="form-group">
            <label>Mood</label>
            <input type="text" id="mood" class="form-control"
                   value="<?=$data->mood?>">
        </div>
        <div class="form-group">
            <label>genre</label>
            <input type="text" id="genre" class="form-control"
                   value="<?=$data->exp?>">
        </div>
    </form>
    <!-- <button onclick="update_item()" class="btn btn-warning">Update</button>
    <button onclick="get_json()" class="btn-primary">Get JSON</button> -->

    <div id="json-representation"></div>

<?php } else { ?>
    <div>No data found.</div>
<?php } ?>

<!-- <script>
    function update_item() {
        const id = document.getElementById("entry_id").value;
        const name = document.getElementById("name").value;
        const entry = document.getElementById("entry").value;
        const description = document.getElementById("description").value;
        const exp = document.getElementById("exp").value;
        fetch(window.location, {
            method: "PUT",
            body: "id= " + id + "&name= " + name + "&entry= " + entry
                + "&description= " + description + "&exp= " + exp
        }).then(response => alert("Updated!"))
    }

    function get_json() {
        const element = document.getElementById("json-representation");
        fetch(window.location, {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        }).then(response => response.json().then(j =>element.innerHTML = JSON.stringify(j)))
    }
</script> -->

<?php include __DIR__."/../_footer.phtml"; ?>
