<?php include __DIR__."/../_header.phtml"; ?>
<?php /** @var Domains_Song $data */ ?>
<?php if ($data) { ?>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Artist</th>
                <th>Mood</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
        <?php
        foreach($data as $obj) {
            ?>
            <tr>
                <td><?=$obj->name?></td>
                <td><?=$obj->artist?></td>
                <td><?=$obj->mood?></td>
               <td><a href="./Song/<?=$obj->id?>" class="link-primary">Details</a></td>
            </tr>
        <?php
        }
        ?>
        </tbody>
    </table>
<?php } ?>

<?php include __DIR__."/../_footer.phtml"; ?>
