<?php include __DIR__ . "/../_header.phtml"; ?>
<?php /** @var Domains_Base $data */ ?>
<?php { ?>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Zentriertes Formular</title>
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </head>

    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Options</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link active" aria-current="page" href="#">Generate Playlist</a>
                        <a class="nav-link disabled" aria-disabled="true">Show Playlists</a>
                    </div>
                </div>
            </div>
        </nav>

        <form>
            <div class="mb-3s">
                <label for="inputUsername" class="form-label">Username</label>
                <input type="username" class="form-control" id="inputUsername">
            </div>
            <div class="mb-3">
                <label for="inputEmail" class="form-label">Email address</label>
                <input type="email" class="form-control" id="inputEmail" aria-describedby="emailHelp">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
            </div>
            <button type="submit" class="btn btn-primary" onclick="event.preventDefault(), getValues()">Login</button>
        </form>
    </body>

    </html>

<?php } ?>

<script>
    function getValues() {
        const email = document.getElementById("inputEmail").value;
        const username = document.getElementById("inputUsername").value;
        console.log("Email: " + email + "\nUsername: " + username);

        console.log(window.location);

        fetch(window.location, {
            method: "POST",
            headers: {
                "Content-Type": "application/x-www-form-urlencoded"
            },
            body: "email=" + email + "&username=" + username
        }).then(response => {
            if (response.ok) {
                console.log("POST request successful.");
            } else {
                console.error("POST request failed.");
            }
        }).catch(error => {
            console.error('Error:', error);
        });
    }
</script>


<?php include __DIR__ . "/../_footer.phtml"; ?>