<?php include __DIR__ . "/../_header.phtml"; ?>
<?php /** @var array $data */ ?>
<?php { ?>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Total Time</th>
                <th>Details</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($data as $item) : ?>
                <tr>
                    <td><?= htmlspecialchars($item->name) ?></td>
                    <td><?= htmlspecialchars($item->totalTime) ?></td>
                    <td><a href="./Playlist/<?= htmlspecialchars($item->id) ?>">View Details</a></td>
                    <td>
                        <button onclick="handleDelete(<?= $item->id ?>)" class="btn btn-danger">Delete</button>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <script>
        async function handleDelete(id) {
            if (confirm('Are you sure you want to delete this playlist?')) {
                try {
                    const response = await fetch(window.location.href, {
                        method: 'DELETE',
                        headers: {
                            'Content-Type': 'application/json'
                        },
                        body: JSON.stringify({
                            id
                        })
                    });

                    if (response.ok) {
                        console.log('Playlist deleted successfully.');
                        location.reload();
                    } else {
                        console.log('Failed to delete the playlist.');
                    }
                } catch (error) {
                    console.error('Error:', error);
                }
            }
        }
    </script>

<?php } ?>

<?php include __DIR__ . "/../_footer.phtml"; ?>